name: Daily xPoints Prediction

on:
  schedule:
    - cron: "30 16 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy tqdm scikit-learn

      # Step 4: Run your prediction script
      - name: Run prediction script
        run: |
          python script.py
        # Replace 'your_script.py' with the filename of your Python script.

      # Step 5: Commit the generated predictions.json back to the repository
      - name: Commit predictions.json to repository
        uses: EndBug/add-and-commit@v9
        with:
          add: "predictions.json"
          message: "Update predictions.json [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
