name: Daily xPoints Prediction

permissions:
  contents: write

on:
  schedule:
    - cron: "30 16 * * *"  # Runs daily at 16:30 UTC
  workflow_dispatch:

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.32.3 pandas==2.2.3 numpy tqdm==4.67.1 scikit-learn==1.4.2 xgboost==1.7.5 python-dateutil==2.9.0.post0

      - name: Check installed package versions
        run: |
          pip list | grep -E 'requests|pandas|numpy|tqdm|scikit-learn|xgboost|python-dateutil'

      - name: Run prediction script
        run: |
          python script.py  # Replace with your actual script filename, e.g., 'fpl_prediction.py'

      - name: Commit predictions.json to repository
        uses: EndBug/add-and-commit@v9
        with:
          add: "predictions.json"
          message: "Update predictions.json [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
